general:
  # Should moni keep running and execute periodically  
  periodic: true
  # If periodic is true, what interval should moni run at? Interval value is in seconds
  interval: 3600
  # Tree is stored as a json to the following path
  tree_store: /app/output.json
  # Path to parse
  path: /var/www/html
  # Command that should run if the tree is identical to the previous one
  command_success: "echo SUCCESS"
  # 
  command_failure: "echo FAILURE"
log:
  # Log path for moni. os path or stdout accepted
  log_path: stdout
  # Memory log options are only for development use. Please keep memory_log value to false
  memory_log_path: ./memory.log
  memory_log: false
algorithm:
  # Algorithm options are:
  # - FlatTreeWalk (manual recursive treewalk)  
  # - GoDirTreeWalk - walk algorithm developed by karrick - https://github.com/karrick/godirwalk
  name: FlatTreeWalk
  processor: ObjectProcessor
  # List of directory / file names moni should ignore
  ignore:
    - ".git"
    - ".idea"
    - ".vscode"
    - ".DS_Store"
    - "node_modules"
    - "uploads"